config/routes.rb
IuguSubscriptionExample::Application.routes.draw do
  root :to => 'index#index'

  devise_for :users

  as :user do
    get 'login' => 'devise/sessions#new', :as => 'new_user_session'
    post 'login' => 'devise/sessions#create', :as => 'user_session'
    delete 'logout' => 'devise/sessions#destroy', :as => 'destroy_user_session' 
    get 'logout' => 'devise/sessions#destroy', :as => 'destroy_user_session' 

    get 'signup' => 'devise/registrations#new', :as => 'new_user_registration'
    post 'signup' => 'devise/registrations#create', :as => 'user_registration'

    post 'forgot_password' => 'devise/passwords#create', :as => 'user_password'
    get 'forgot_password' => 'devise/passwords#new', :as => 'new_user_password'
    get 'forgot_password/edit' => 'devise/passwords#edit', :as => 'edit_user_password'
    put 'forgot_password' => 'devise/passwords#update', :as => 'update_user_pasword'
  end

  get 'subscribe' => 'subscription#subscribe', as: 'subscribe'
  post 'subscribe' => 'subscription#subscribe_to_plan', as: 'subscribe_to_plan'
  get 'a' => 'app#home', as: 'app_home'

  get 'profile' => 'profile#view', as: 'profile'
  get 'profile/new_payment_method' => 'profile#new_payment_method', as: 'profile_new_payment_method'
  post 'profile/create_payment_method' => 'profile#create_payment_method', as: 'profile_create_payment_method'
  delete 'profile/delete_payment_method/:id' => 'profile#delete_payment_method', as: 'profile_delete_payment_method'
  post 'profile/default_payment_method/:id' => 'profile#default_payment_method', as: 'profile_default_payment_method'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  def subscribed?
    !!subscription_id
  end

  def customer
    unless customer_id
      customer = Iugu::Customer.create({ email: email }) rescue false
      update_attribute :customer_id, customer.id
      return customer
    end

    Iugu::Customer.fetch(customer_id) rescue nil
  end

  def subscription
    Iugu::Subscription.fetch(subscription_id) if subscribed?
  end

  def payment_methods
    Iugu::PaymentMethod.search({customer_id: customer_id}).results rescue []
  end

  def invoices
    Iugu::Invoice.search( customer_id: customer_id ).results rescue []
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  before_filter :authenticate_user!
  before_filter :verify_subscription

  def home
    
  end

  private

  def verify_subscription
    redirect_to subscribe_path unless current_user.subscribed?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
    
  end

end

app/controllers/profile_controller.rb
#encoding: utf-8
class ProfileController < ApplicationController

  before_filter :authenticate_user!

  def view
    @user = current_user
    @customer = @user.customer
    @subscription = @user.subscription
    @payment_methods = @user.payment_methods
    @invoices = @user.invoices
  end

  def new_payment_method
  end

  def create_payment_method
    @user = current_user
    customer = current_user.customer

    @payment_method = customer.payment_methods.create({
      description: params[:description],
      token: params[:credit_card_token]
    })

    logger.info "Payment ---- #{@payment_method.inspect}"
    
    redirect_to profile_path
  end

  def delete_payment_method
    pm = current_user.customer.payment_methods.fetch(params[:id])
    pm.delete

    redirect_to profile_path
  end

  def default_payment_method
    customer = current_user.customer
    pm = customer.payment_methods.fetch(params[:id])

    if(pm.id)
      customer.default_payment_method_id = pm.id
      customer.save
    end

    redirect_to profile_path
  end

end

app/controllers/subscription_controller.rb
#encoding: UTF-8
class SubscriptionController < ApplicationController
  before_filter :authenticate_user!

  def subscribe
    if params[:p]
      @plan = Iugu::Plan.fetch_by_identifier(params[:p]) rescue nil
    end
    @user = current_user
    @customer = @user.customer
    @plans = Iugu::Plan.search.results unless @plan
    @payment_method = "credit_card"
    @cards = @user.payment_methods

  end

  def subscribe_to_plan
    customer = current_user.customer

    if params[:payment_method] == "credit_card"
      customer.payment_methods.create({
        description: "Cartão de Crédito",
        token: params[:credit_card_token],
        set_as_default: true
      })
    end

    sub_params = {
      plan_identifier: params[:plan_identifier],
      customer_id: customer.id
    }
    sub_params[:only_on_charge_success] = true if params[:payment_method] == "credit_card"

    subscription = Iugu::Subscription.create(sub_params)

    if subscription.errors
      @plan = Iugu::Plan.fetch_by_identifier(params[:plan_identifier])
      @payment_method = params[:payment_method]
      @error = "Erro na Cobrança!"
      return render :subscribe
    end

    current_user.subscription_id = subscription.id
    current_user.save

    redirect_to profile_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app/home.html.erb
HOME!

app/views/index/index.html.erb
Bem vindo ao Have a Coffee

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IuguSubscription</title>
  <%= stylesheet_link_tag    "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", :media => "all" %>
  <%= stylesheet_link_tag    "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css", :media => "all" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://js.iugu.com/v2" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Subscription</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><a href="/subscribe">Assine</a></li>
                  <li><a href="/profile">Minha Conta</a></li>
                </ul>
              </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
          </nav>
    <%= yield %>
  </div>

  <%= javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js" %>
</body>
</html>

app/views/subscription/subscribe.html.erb
<% unless @plan %>
  <div class="page-header">
    <h1>Selecione um Plano</h1>
  </div>
  <div class="row">
    <% @plans.reverse.each do |plan| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <div class="caption">
            <h3><%= plan.name %></h3>
            <h4>R$ <%= plan.prices[0]["value_cents"] / 100 %> / <%= (plan.interval_type == "months") ? "Mês" : "Semana" %></h4>
            <ul class="features">
              <% plan.features.each do |feature| %>
                <li class="<%= "important-feature" if feature["important"] == "true" %>">
                  <%= feature["value"] %> <%= feature["name"] %>
                </li>
              <% end %>
            </ul>
            <p>
              <%= link_to "Assinar", subscribe_path(p: plan.identifier), { class: "btn btn-block btn-primary" } %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="page-header">
    <h1>Assinar <%= @plan.name if @plan %></h1>
  </div>
  <form method="POST" action="<%= subscribe_to_plan_path %>">
    <% if @error %>
      <div class="form_error alert alert-danger">
        <strong>
          Erro!!!
        </strong>
        <p><%= @error %></p>
      </div>
    <% end %>

    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
    <input id="plan_identifier" name="plan_identifier" type="hidden" value="<%= @plan.identifier %>"/>
    <input id="credit_card_token" name="credit_card_token" type="hidden" value="<%= @credit_card_token || "" %>"/>
    <div class="form-horizontal">
      <div class="payment-select">
        <div class="btn-group btn-group-lg" data-toggle="buttons">
          <label class="btn btn-default credit_card" class="<%= "active" if @payment_method == "credit_card" %>">
            <%= radio_button_tag 'payment_method', 'credit_card', (@payment_method == "credit_card") %>
            Cartão de Crédito
          </label>
          <label class="btn btn-default bank_slip" class="<%= "active" if @payment_method == "bank_slip" %>">
            <%= radio_button_tag 'payment_method', 'bank_slip', (@payment_method == "bank_slip") %>
            Boleto Bancário
          </label>
          <label class="btn btn-default onclick_card_details" class="<%= "active" if @payment_method == "credit_card" %>">
            <%= radio_button_tag 'payment_method', 'credit_card', (@payment_method == "credit_card") %>
            Cartão Padrão
          </label>
        </div>
      </div>
      <div id="credit_card_details">
        <div class="well">
          <div class="cc_error alert alert-danger">
            <strong>
              Erro!!!
            </strong>
            Cartão de crédito inválido.
          </div>
          <div style="text-align: center"><%= image_tag "aceitamos.jpg", style: "padding-bottom: 20px" %></div>
          <div class="data-group">
            <div class="credit_card_type"></div>
            <input class="form-control credit_card_number" placeholder="Número do Cartão" type="text" data-iugu="number" value="" autocomplete="off" />
            <input class="form-control credit_card_name" placeholder="Nome no Cartão" type="text" value="" autocomplete="off" />
            <input class="form-control credit_card_expiration" data-iugu="expiration" placeholder="MM/AA" type="text" autocomplete="off" value="" />
          </div>
          <div class="well cvv" style="position: relative;">
            <div class="credit_card_cvv_type"></div>
            <input class="form-control credit_card_cvv" data-iugu="verification_value" placeholder="CVV" type="text" autocomplete="off" value="" />
            <span>Código de Segurança</span>
          </div>
          <input class="form-control credit_card_first_name" data-iugu="first_name" placeholder="Nome" type="hidden" autocomplete="off" value="" />
          <input class="form-control credit_card_last_name" data-iugu="last_name" placeholder="Sobrenome" type="hidden" autocomplete="off" value="" />

          <div style="text-align: right;">
            <%= image_tag "pagamentos-por-iugu-linhas-escuro.png", style: "padding-top: 10px" %>
          </div>
        </div>
      </div>
      <div id="onclick_card_details">
        <div class="row">
        <div class="col-md-offset-2 col-md-8">
          <table class="table table-condensed table-responsive">
            <thead>
              <tr>
                <th>Descrição</th>
                <th>Cartão</th>
                <th>Token</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @cards.each do |payment_method| %>
                <tr class="<%= "active" if @customer.default_payment_method_id == payment_method.id %>">
                  <td><%= payment_method.description %></td>
                  <td><%= payment_method.data['brand'] + " " + payment_method.data['display_number'] %></td>
                  <td><a id="payment" onclick=$('#credit_card_token').val('<%= payment_method.id %>'); class: "btn btn-xs btn-danger" > Usar Cartão </a></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
      <div class="subscribe-button">
        <button class="btn btn-danger btn-lg" type="submit">
          Assinar
        </button>
      </div>
    </div>
  </form>
<% end %>